### ISSUE TITLE
Maps.me

### ISSUE THREAD

**Issue by karussell** [matkoniecz/illegal-use-of-OpenStreetMap#1]
Just fyi: if you open Maps.me there is already an OSM attribution but very short like 2 or 3 seconds in the bottom left corner of the map.

**Comment by matkoniecz** [comment]
Thanks for mentioning it!

Is it appearing only on the first run or is in other way limited? I just tested in on my phone and it is not appearing. Can you check is it always appearing on your phone?

It is still not sufficient to cover ODBL attribution requirements but it should be mentioned (like attribution deeply buried in settings is not sufficient but is mentioned).

**Comment by karussell** [comment]
If you close it explicitly it appears. But yes, once opened it does not reappear.

> It is still not sufficient to cover ODBL attribution requirements

Yes

**Comment by matkoniecz** [comment]
What is your phone? Are you using maybe an iPhone version of maps.me? I tried reproducing this and failed so far.

Are you maybe willing to record screencast of this attribution flashing and sharing it?

--------

I just tried reinstalling, but it failed to purge my setting from the phone.

So when I uninstalled it and installed it again, it restored for example my saved locations and it no longer made the attribution flash.

I tried cleaning data from "Apps & notifications" -> "MAPS.ME" -> "Storage" -> "Clear storage". It also failed to clear data.

I now deleted MapsWithMe folder on the memory card. It also failed to delete data, for example marker on the map.

I now uninstalled app, found deleted MapsWithMe folder on the built-in drive and restarted the phone. This finally removed my data.

The flash attribution still failed to appear.

**Comment by karussell** [comment]
> What is your phone? Are you using maybe an iPhone version of maps.me?

Have tried it for Android, using version 9.1.8-Google. But I can confirm this attribution does never appear for iPhone.

> The flash attribution still failed to appear after installing the app.

Hmmh, strange. No idea.

**Comment by matkoniecz** [comment]
I borrowed phone, it was appearing there. For now there is an .mp4 file with screen capture in the repo - https://github.com/matkoniecz/illegal-use-of-OpenStreetMap/blob/master/MAPS.ME/attribution_flash.mp4

I still need to mention it in the descriptions.
