### ISSUE TITLE
Is this list constantly being reviewed?

### ISSUE THREAD

**Issue by bkil** [matkoniecz/illegal-use-of-OpenStreetMap#26]
I think such a site intending to be a wall of shame should put more effort on staying up to date (if this goal is any good anyway)

Mapbox seems to display attribution in the lower right as expected in a desktop web browser as of now on a page similar to the screenshot: `api.mapbox.com/styles/v1/mapbox/streets-v11.html?...`

See also the comment about this on the wiki talk page.

**Comment by matkoniecz** [comment]
> Mapbox seems to display attribution in the lower right as expected in a desktop web browser as of now on a page similar to the screenshot: api.mapbox.com/styles/v1/mapbox/streets-v11.html?...

It was displaying also when I made this page.

Is it displaying it on mobile devices, AKA how more and more people use websites?

**Comment by matkoniecz** [comment]
> This specific image is from one of their example pages. It has no real attribution when opened on a mobile or when browser window is resized to a smaller one.

**Comment by matkoniecz** [comment]
Tested on small window, plagiarism still present:

![screen08](https://user-images.githubusercontent.com/899988/117568064-ff64c100-b0be-11eb-8573-f03ab32911b6.png)

**Comment by bkil** [comment]
Maybe I'm not doing something right. I visited this page and checked out both the embedding at the bottom and the one on the style preview page and they both showed attribution to me:
- https://www.mapbox.com/maps/streets#the-data
![mapbox_attribution_preview](https://user-images.githubusercontent.com/818763/117569145-87999500-b0c4-11eb-8d90-73c4e02feaec.png)
![mapbox_attribution_preview_tiny_clicked](https://user-images.githubusercontent.com/818763/117569147-8d8f7600-b0c4-11eb-9610-b9f894905648.png)
![mapbox-attribution-showcase](https://user-images.githubusercontent.com/818763/117569155-95e7b100-b0c4-11eb-9da0-b348eac04dd3.png)
![mapbox-attribution-showcase-tiny-hovered](https://user-images.githubusercontent.com/818763/117569158-997b3800-b0c4-11eb-93db-ebdb8dfd63df.png)

Did you try clicking the information button in the corner on your mobile?

**Comment by matkoniecz** [comment]
> Did you try clicking the information button in the corner on your mobile?

Yes, I know that if someone will click on hidden (i) then some attribution will appear. See

> Mention of the real source of map data is hidden by default on mobile devices.

in https://github.com/matkoniecz/illegal-use-of-OpenStreetMap/blob/master/Mapbox/Mapbox.md

Maybe mentioning explicitly that some attribution is shown on large screens and after clicking on i dot attribution will also appear on mobile would be a good idea?

**Comment by matkoniecz** [comment]
> and they both showed attribution to me:

You needed to interact with page to get it displayed (clicking on black dot), right?

**Comment by matkoniecz** [comment]
Closing due to no response - feel free to respond to my questions and I will reopen it.

As far as I know text is up to date, let me know if I missed something.

**Comment by bkil** [comment]
Why was this issue closed? Did you add the column for the last check date? Did you remove Mapbox from the list? Let me share some sources with you (emphasis mine).

- https://opendatacommons.org/licenses/odbl/1-0/
> 4.2 d. If it is not possible to put the required notices in a particular file due to its structure, then You must include the notices in a location (such as a relevant directory) **where users would be likely to look for it**.
> 4.3 Notice for using output (Contents). Creating and Using a Produced Work does not require the notice in Section 4.2. However, if you Publicly Use a Produced Work, You must include a notice associated with the Produced Work reasonably calculated to make any Person that uses, views, accesses, **interacts with**, or is otherwise exposed to the Produced Work aware that Content was obtained from the Database, Derivative Database, or the Database as part of a Collective Database, and that it is available under this License.

- https://wiki.osmfoundation.org/wiki/Licence/Licence_and_Legal_FAQ#Where_to_put_it.3F
> For a browsable electronic map (e.g. embedded in a web page or mobile phone application), the credit should typically appear **in the corner of the map, as commonly seen with map APIs/libraries such as Google Maps**.

- https://wiki.osmfoundation.org/wiki/Licence/Community_Guidelines/Produced_Work_-_Guideline
> "Produced Work" is a term used by ODbL to broadly separate something created from a database but not a database itself. For OpenStreetMap, this often means a map, [...]

According to these, it is acceptable if attribution appears similarly to the way how other slippymap providers show their own. It is common that if the display port is too small to show the long variant, then it will only appear on interaction, like on hovering or after clicking on it. It is not buried within legal documents under hierarchical menus or behind long list of credits - it's just an `(i)` (information) button that automatically expands to the full to the full text.

Also note that omitting the phrase _"and contributors"_ is also acceptable:

- https://wiki.osmfoundation.org/wiki/Licence/Community_Guidelines/Produced_Work_-_Guideline
> Because OpenStreetMap is its contributors, you may omit the word "contributors" if space is limited.

Note that I've proven it with many screenshots that if the window or the screen resolution is big enough, the text is shown in full and it only gets compressed as dictated by the responsive design if it would use more space than just a corner.

Regardless of whether your opinion would hold up in court, you are not doing any good to the community by openly attacking and daemonizing those who are doing a reasonable job at trying to include attribution and offloading our servers just because they make money out of it.

**Comment by matkoniecz** [comment]
reopening as answer appeared

**Comment by matkoniecz** [comment]
> Regardless of whether your opinion would hold up in court, you are not doing any good to the community by openly attacking and daemonizing those who are doing a reasonable job at trying to include attribution and offloading our servers just because they make money out of it.

My position is that that hidden attribution is not doing a reasonable job at including attribution.

"they make money out of it." is not a part of the problem, except that for organization with large budget the excuse "we are incapable of implementing" is not viable and it is far more likely that decision made is deliberate, not accidental.

**Comment by bkil** [comment]
I would think that they have more than enough funds for their legal department to have verified the licensing terms in depth beforehand.

**Comment by matkoniecz** [comment]
> I would think that they have more than enough funds for their legal department to have verified the licensing terms in depth beforehand.

Yes, but that does mean that they would be able to conclude that OSMF is toothless in enforcing attribution requirement and it is safe to ignore them.

Companies repeatedly violate law where it is poorly enforced or where they hope that it will be poorly enforced. Or where involved people hope that they will not be punished. See Enron, truck pricing collusion etc.

Or https://en.wikipedia.org/wiki/Phoebus_cartel https://en.wikipedia.org/wiki/Lysine_price-fixing_conspiracy https://en.wikipedia.org/wiki/Bhopal_disaster https://en.wikipedia.org/wiki/Minamata_disease 

> Pollution was so heavy at the mouth of the wastewater canal, a figure of 2 kg of mercury per ton of sediment was measured: a level that would be economically viable to mine. Indeed, Chisso did later set up a subsidiary to reclaim and sell the mercury recovered from the sludge.

For example Facebook is known to be violating law, especially privacy related ones. See https://9to5mac.com/2019/05/28/gdpr-fines/ https://www.theguardian.com/technology/2018/feb/12/facebook-personal-data-privacy-settings-ruled-illegal-german-court  

And no, it is not just courts being anti-Facebook or Facebook missing some trap. It is Facebook being evil and maliciously, deliberately and illegally violating rules.

For an extreme case of what their legal department invented see https://noyb.eu/en/facebooks-gdpr-bypass-reaches-austrian-supreme-court

> When the GDPR came into effect, one big benefit was the duty to have a clear opt-in consent when companies want to process user data. In addition to consent, there are five other legal bases to process data under Article 6(1) GDPR. One of these basis is processing that is "necessary for the performance of a contract". On 25.5.2018 at midnight, when the GDPR became applicable, Facebook has simply named things like "personalized advertisement" in its terms and conditions. Facebook now argues that it has a "duty to provide personalized advertisement" to the users, therefore, it does not need the user's consent to process his or her personal data.

So overall I trust legal departments of companies to invent excuses - sometimes serious, sometimes just officialy sounding babble. But  it would be all designed to excuse company, interpret law as allowing what they want, removing legal obligation and giving them excuses to do things from paying lower taxes, through polluting and being not legally responsible to deaths expected to happen due to what company did.

And some of their actions/analysis would be countering equally biased analysis - just with a different slant.

But trusting that major organization legal department is not biased is ridiculous.

And it does not apply to only companies! It applies to whoever paid for layer to get the best interpretation for them that still can be seriously treated!

**Comment by bkil** [comment]
One last comment based on this thread and our other communication on the mailing list and wiki: would there be any reasoning that could change your mind or are you already decided on an agenda?

> My position is that that hidden attribution is not doing a reasonable job at including attribution.

As outlined in depth above, attribution is not hidden in any reasonable sense of the word: it is where people expect to find it and done similarly how many other map providers are doing it on tiny screens. Interaction was never ruled out in the licensing terms - on the contrary, it was mentioned explicitly.

_"Doing a reasonable job according to **your** opinion"_ is not something that a court would be testing. It would be testing the usage against the licensing terms, and I can see no conflict here. I have a feeling that you are kind of left alone with your opinion here, but if in doubt, you could open a poll about this on a public place like the mailing list.

I failed to find on topic arguments regarding the issue at hand in the last comment as I could find none of the listed examples provide a good enough parallel to prove anything. I also find it offensive to compare anyone to Facebook. If they were allowed to use less personalization, they would lose targeting and hence may face a 50% decrease in revenue that is clearly unacceptable, so they have a vested interested against doing certain things.

At the same time, I fail to see what advantage Mapbox could gain by deliberately "hiding" attribution behind the information button in the corner of the map in small resolutions, this sounds more like a conspiracy theory. Also note that they "hide" the full attribution, both theirs and OSM's, not just OSM's on small screens. However, if the attribution would not be collapsed, it would occupy the whole lower part of the screen, that could be kind of irritating when navigating the map for long. Or alternatively, it could be shown in the corner in tiny letters, but that would also raise an issue here in one of your folders and even worse: that would actually be against the licensing terms, as it **does** have a rule against showing the attribution in too small letters.

**Comment by bkil** [comment]
By the way, did you notice that mapillary.com uses the same `(i)` information icon in the lower right corner that only displays attribution on mouse hover even on full HD screens?

**Comment by matkoniecz** [comment]
I opened  "make clear when each page was reviewed" #28 - idea is good and it would be good to no lose it after this issue is closed

> Did you remove Mapbox from the list? Let me share some sources with you (emphasis mine).

No, as I am convinced that Mapbox violates OSM license, at least in case presented here.

> According to these, it is acceptable if attribution appears similarly to the way how other slippymap providers show their own

(1) this is not true - if slippymap providers show no attribution at all this does not waive attribution required by ODbL

(2) this is clearly not happening in this case - note how much space if used for attributing Mapbox and how much for attributing OpenStreetMap (closeup to attribution part on mobile)

Full image is shown at https://github.com/matkoniecz/illegal-use-of-OpenStreetMap/blob/master/Mapbox/Mapbox.md#map-without-a-proper-attribution

![screen03](https://user-images.githubusercontent.com/899988/121779961-77cb1000-cb9e-11eb-8596-46cfeebebc49.png)

> Also note that omitting the phrase "and contributors" is also acceptable:

I am not disputing this, I am not using that part also on maps that I produce.

> Note that I've proven it with many screenshots that if the window or the screen resolution is big enough, the text is shown in full and it only gets compressed as dictated by the responsive design if it would use more space than just a corner.

Note that in Mapbox case there is sufficient space to attribute Mapbox three times and not enough space to attribute OpenStreetMap even once.

In reality there is enough to fit real attribution just in a blank unused space, there is enough space to fit second attribution bar...

Also, responsive design is not waiving ODbL requirements anyway.

> Regardless of whether your opinion would hold up in court, you are not doing any good to the community by openly attacking and daemonizing those who are doing a reasonable job at trying to include attribution and offloading our servers just because they make money out of it.

In Mapbox case there is the found space to attribute Mapbox three times and failed to find space to attribute OpenStreetMap even once.

This is not a reasonable job at trying to include attribution.

Yes, I am openly attacking them and consider it as justified. Whole point of https://github.com/matkoniecz/illegal-use-of-OpenStreetMap is to document willful violation of OpenStreetMap licence by entities such as Mapbox, Snapchat, Facebook or PKP.

**Comment by matkoniecz** [comment]
> One last comment based on this thread and our other communication on the mailing list and wiki: would there be any reasoning that could change your mind or are you already decided on an agenda?

Analysis from lawyer without conflict of interest or court decisions.

Such things would be able to convince me that not including clearly visible attribution, when license specifically requires clearly visible attribution is nevertheless somehow not illegal (beyond fair use and similar rules not applying in cases discussed here).

Though I would still consider it as unethical and nasty behaviour.

**Comment by matkoniecz** [comment]
> As outlined in depth above, attribution is not hidden in any reasonable sense of the word: it is where people expect to find it and done similarly how many other map providers are doing it on tiny screens. 

License requires attribution clearly visible to all users. Putting it behind [mystery meat navigation](https://en.wikipedia.org/wiki/Mystery_meat_navigation) where you need to click on stuff to learn what is there is not fulfilling ODbL attribution requirements and would require really twisted reasoning to support such legal argument (I have seen more hilarious legal analysis, so it is not out of picture).

> Interaction was never ruled out in the licensing terms - on the contrary, it was mentioned explicitly.

Word interaction is used, bot not in any way related to allowing attribution hiding.

> "Doing a reasonable job according to your opinion" is not something that a court would be testing. 

Definitely.

> It would be testing the usage against the licensing terms, and I can see no conflict here. I have a feeling that you are kind of left alone with your opinion here, but if in doubt, you could open a poll about this on a public place like the mailing list.

Well, in this case we clearly disagree and I am unable to offer unbiased view here.

> I failed to find on topic arguments regarding the issue at hand in the last comment as I could find none of the listed examples provide a good enough parallel to prove anything. 

I was arguing against "I would think that they have more than enough funds for their legal department to have verified the licensing terms in depth beforehand." argument. Companies definitely did plenty of illegal things before.

> I also find it offensive to compare anyone to Facebook.

Facebook is one of companies using OSM data without proper attribution, and if other companies reply they reply with insanely twisted reasoning resembling FB legal arguments on privacy topic.

> At the same time, I fail to see what advantage Mapbox could gain by deliberately "hiding" attribution behind the information button in the corner of the map in small resolutions

(1) there is more space to promote own brand

(2) yes, adding attribution makes map uglier (I also was tempted to not include attribution when I made OMS-based maps)

> Also note that they "hide" the full attribution, both theirs and OSM's, not just OSM's on small screens.

Is https://raw.githubusercontent.com/matkoniecz/illegal-use-of-OpenStreetMap/master/Mapbox/Mapbox_attributes_itself_2019-12-30.png image outdated?

**Comment by matkoniecz** [comment]
> It would be testing the usage against the licensing terms, and I can see no conflict here. I have a feeling that you are kind of left alone with your opinion here, but if in doubt, you could open a poll about this on a public place like the mailing list.

See for example https://wiki.openstreetmap.org/wiki/Draft_Attribution_Guideline/2021v0.9

> The attribution format should not require individuals to interact with the map or produced work to see the attribution.

**Comment by matkoniecz** [comment]
"make clear when each page was reviewed" that was tracked by #28  is now implemented.

It also allowed me to spot that MAPS.ME achieved further reduction of visibility of already barely visible attribution.

I documented it in https://github.com/matkoniecz/illegal-use-of-OpenStreetMap/blob/master/MAPS.ME/MAPS.ME.md#mapsme-is-using-openstreetmap-data-illegally

I see no need for other changes.
