### ISSUE TITLE
Check whatever Instagram app for Apple is using OSM maps without a proper attribution

### ISSUE THREAD

**Issue by matkoniecz** [matkoniecz/illegal-use-of-OpenStreetMap#3]
Has anybody got an access to both an Instagram account and an Apple device? And can check whatever it is part of the problem?

Things to check
- [ ] are there any maps or geographic data in this app?
- [ ] is it from OSM?
- [ ] is it clearly credited to OSM?

**Comment by grischard** [comment]
It uses Apple Maps. Which uses OSM without attribution in, e.g., Denmark, but that's an issue for another ticket :).

**Comment by matkoniecz** [comment]
Thanks for checking! I created #12 for Apple, it would be useful to have a screenshot that makes clear

- that there is no proper attribution
- they have data coped from OSM

I have limited access to apple devices, so if anyone is able to do this - feel free to comment in #12 with an attached screenshot or send me an email ( matkoniecz@tutanota.com ).

**Comment by matkoniecz** [comment]
And in case you are interested in checking more apps - there is #13 (Facebook local) and #11 (Snapachat, account may be created with a disposable mail)
