### ISSUE TITLE
WMF seem to have found a compromise between attribution and screen real estate

### ISSUE THREAD

**Issue by dpriskorn** [matkoniecz/illegal-use-of-OpenStreetMap#32]
before hover
![bild](https://user-images.githubusercontent.com/68460690/128368611-3312a205-b9f0-4698-a405-d3590e3666a3.png)
after hover
![bild](https://user-images.githubusercontent.com/68460690/128368596-00247f46-300a-417b-8e89-f88e47bbc594.png)
https://www.wikidata.org/wiki/Q6477226

I think this is OK. 
WDYT?

**Comment by matkoniecz** [comment]
I think that initial one is not ideal and not fully attributing, but they clearly tried so I am not going to list them here or on https://wiki.openstreetmap.org/wiki/Lacking_proper_attribution

But they should still show proper attribution and shorten either "Wikimedia maps" self-attribution or scale.

Note: I am not a lawyer.
